#!/bin/sh

load_module() {
  module_name=$1
  # remove first parameter to get the rest of the files specified
  shift
  create_device="$*"
  modprobe "$module_name" || exit 1
  if [ "$create_device" ]; then
    major_number=$(awk '$2=="'"$module_name"'" {print $1}' </proc/devices)
    for device in $create_device; do
      mknod "$device" c "$major_number" 0
    done
  fi
}

unload_module() {
  module_name=$1
  # remove first parameter to get the rest of the files specified
  shift
  rm_device="$*"
  if [ "$rm_device" ]; then
    for device in $rm_device; do
      rm -rf "$device"
    done
  fi
  rmmod "$module_name" || exit 1
}

case "$1" in
"start")
  load_module aesdchar /dev/aesdchar
  ;;
"stop")
  unload_module aesdchar /dev/aesdchar
  ;;
*)
  echo "Usage: $0 [start|stop]"
  ;;
esac
